import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Editorial Tech-Boutique — Light Mode
        'background': '#FBF9F6',
        'foreground': '#242424',
        'canvas': '#FBF9F6',
        'text-primary': '#242424',
        'text-secondary': '#555555',
        // Brand accent (terracotta)
        'primary': '#A85838',
        'primary-container': '#C97A5B',
        'on-primary': '#FFFFFF',
        'on-primary-container': '#FFFFFF',
        'primary-fixed': '#A85838',
        'primary-fixed-dim': '#C97A5B',
        'on-primary-fixed': '#FFFFFF',
        'on-primary-fixed-variant': '#FFFFFF',
        'primary-dim': '#C97A5B',
        'inverse-primary': '#C97A5B',
        'accent': '#A85838',
        'accent-hover': '#8E472B',
        // Lime — graphic/marker only
        'secondary': '#96E600',
        'secondary-container': '#96E600',
        'on-secondary': '#242424',
        'on-secondary-container': '#242424',
        'secondary-fixed': '#96E600',
        'secondary-fixed-dim': '#96E600',
        'on-secondary-fixed': '#242424',
        'on-secondary-fixed-variant': '#242424',
        'secondary-dim': '#96E600',
        'lime': '#96E600',
        // Decorative — muted neutrals (quiet editorial)
        'cyan': '#555555',
        'cyan-light': '#888888',
        'blue': '#555555',
        'blue-light': '#888888',
        'orange': '#A85838',
        'orange-light': '#C97A5B',
        'green': '#12B76A',
        'green-light': '#6ee7b7',
        'purple': '#555555',
        'purple-light': '#888888',
        'tertiary': '#F5F2EE',
        'tertiary-container': '#EFEAE4',
        'on-tertiary': '#242424',
        'on-tertiary-container': '#242424',
        'tertiary-fixed': '#EFEAE4',
        'tertiary-fixed-dim': '#EBE4DC',
        'on-tertiary-fixed': '#242424',
        'on-tertiary-fixed-variant': '#242424',
        'tertiary-dim': '#EFEAE4',
        // Status
        'error': '#D92D20',
        'error-container': '#FBEAE8',
        'on-error': '#FFFFFF',
        'on-error-container': '#B42318',
        'error-dim': '#D92D20',
        'success': '#12B76A',
        'success-light': '#6ee7b7',
        'warning': '#D92D20',
        'warning-bg': '#FBEAE8',
        'success-bg': '#F0FAF5',
        // Surfaces — cream ladder
        'surface': '#FFFFFF',
        'surface-bright': '#EFEAE4',
        'surface-container': '#F5F2EE',
        'surface-container-high': '#EFEAE4',
        'surface-container-highest': '#EBE4DC',
        'surface-container-low': '#FBF9F6',
        'surface-container-lowest': '#FFFFFF',
        'surface-dim': '#FBF9F6',
        'surface-tint': '#A85838',
        'surface-variant': '#EFEAE4',
        'on-surface': '#242424',
        'on-surface-variant': '#555555',
        'inverse-surface': '#242424',
        'inverse-on-surface': '#FBF9F6',
        'outline': '#B5AFA6',
        'outline-variant': '#E5E0D8',
      },
      fontFamily: {
        headline: ['Assistant', 'sans-serif'],
        body: ['Assistant', 'sans-serif'],
        label: ['Assistant', 'sans-serif'],
        ui: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'sm': '0.125rem',
        'md': '0.5rem',
        'lg': '0.75rem',
        'xl': '1rem',
        'full': '9999px',
      },
      boxShadow: {
        'primary-glow': '0 10px 40px rgba(0, 0, 0, 0.06)',
        'card': '0 10px 40px rgba(0, 0, 0, 0.06)',
        'card-hover': '0 16px 48px rgba(0, 0, 0, 0.08)',
      },
      transitionTimingFunction: {
        'premium': 'cubic-bezier(0.16, 1, 0.3, 1)',
      },
    },
  },
  plugins: [],
};

export default config;
