import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'background': '#0e0e0e',
        'foreground': '#ffffff',
        'primary': '#84cc16',
        'primary-container': '#a3e635',
        'on-primary': '#3a5f00',
        'on-primary-container': '#1f3700',
        'primary-fixed': '#84cc16',
        'primary-fixed-dim': '#a3e635',
        'on-primary-fixed': '#2d4b00',
        'on-primary-fixed-variant': '#416a00',
        'primary-dim': '#a3e635',
        'inverse-primary': '#416a00',
        'secondary': '#d946ef',
        'secondary-container': '#e879f9',
        'on-secondary': '#3d0047',
        'on-secondary-container': '#fff5fa',
        'secondary-fixed': '#e879f9',
        'secondary-fixed-dim': '#e879f9',
        'on-secondary-fixed': '#5e006c',
        'on-secondary-fixed-variant': '#8c00a0',
        'secondary-dim': '#e879f9',
        'cyan': '#06b6d4',
        'cyan-light': '#67e8f9',
        'blue': '#2563eb',
        'blue-light': '#60a5fa',
        'orange': '#f59e0b',
        'orange-light': '#fcd34d',
        'green': '#10b981',
        'green-light': '#6ee7b7',
        'purple': '#7c3aed',
        'purple-light': '#a78bfa',
        'tertiary': '#fffade',
        'tertiary-container': '#f9f05a',
        'on-tertiary': '#666100',
        'on-tertiary-container': '#5d5900',
        'tertiary-fixed': '#f9f05a',
        'tertiary-fixed-dim': '#ebe14e',
        'on-tertiary-fixed': '#4a4600',
        'on-tertiary-fixed-variant': '#686300',
        'tertiary-dim': '#ebe14e',
        'error': '#D92D20',
        'error-container': '#b92902',
        'on-error': '#450900',
        'on-error-container': '#ffd2c8',
        'error-dim': '#D92D20',
        'success': '#12B76A',
        'success-light': '#6ee7b7',
        'warning': '#D92D20',
        'warning-bg': '#0f0f0f',
        'success-bg': '#0f0f0f',
        'surface': '#0e0e0e',
        'surface-bright': '#2c2c2c',
        'surface-container': '#191a1a',
        'surface-container-high': '#1f2020',
        'surface-container-highest': '#262626',
        'surface-container-low': '#131313',
        'surface-container-lowest': '#000000',
        'surface-dim': '#0e0e0e',
        'surface-tint': '#84cc16',
        'surface-variant': '#262626',
        'on-surface': '#ffffff',
        'on-surface-variant': '#e5e5e5',
        'inverse-surface': '#fcf9f8',
        'inverse-on-surface': '#565555',
        'outline': '#767575',
        'outline-variant': '#484848',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'Heebo', 'sans-serif'],
        body: ['Inter', 'Heebo', 'sans-serif'],
        label: ['Inter', 'Heebo', 'sans-serif'],
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'sm': '0.125rem',
        'md': '0.5rem',
        'lg': '0.75rem',
        'xl': '1rem',
        'full': '9999px',
      },
      boxShadow: {
        'primary-glow': '0px 10px 40px rgba(177, 254, 77, 0.15)',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
};

export default config;
